using Wired


function testwire1()
    # Test calculation of Bfield generated by infinite Wire with infinitesimal cross-section

    println("Testing Wire - Infinitesimal Cross-Section")

    Iwire = 1000
    r = 1.0
    wire = Wire([0,0,-10000],[0,0,10000],Iwire,0)
    loc = [r 0 0]

    B = bfield(loc, [wire])

    if isapprox(B[2], mu0*Iwire/(2*pi*r))
        return true 
    else 
        return false 
    end 

end 


function testwire2()
    # Test calculation of Bfield generated by infinite Wire with finite cross-section

    println("Testing Wire - Finite Cross-Section")

    Iwire = 1000
    r = 1.0
    R = 1.0
    wire = Wire([0,0,-10000],[0,0,10000],Iwire,R)
    loc = [r 0 0]

    B = bfield(loc, [wire])

    if isapprox(B[2], mu0*Iwire*R/(2*pi*r^2))
        return true 
    else 
        return false 
    end 

end 

