using Wired
using BenchmarkTools
function testkernel1()
    # Test calculation of Bfield generated by infinite Wire with infinitesimal cross-section

    println("Testing Ckernel Wire - Infinitesimal Cross-Section")

    Iwire = 100000000
    r = 5
    wire = Wire{Float32}([0,0,-10000],[0,0,10000],Iwire, 0)
    loc = Float32.([r 0 0; 2*r 0 0])

    B = Wired.biotsavart_ckernel(loc, [wire])

    return B, mu0*Iwire/(2*pi*r)

end 

display(testkernel1())


function createwireproblem(N)
    # Create a Wire source problem that results in N^2 Biot-Savart computations
    # Nnodes = Nwires = N 

    nodes = rand(Wired.precision, N, 3) 
    wires = Vector{Wired.Wire{Wired.precision}}(undef, N) 

    for i in range(1, N) 
        wires[i] = Wire(rand(3), rand(3), randn(), randn())
    end 

    return nodes, wires
end 

N = 1000 

Wired.precision = Float32
nodes, wires = createwireproblem(N);
wires = [w for w in wires[1:10]]

Wired.biotsavart_ckernel(nodes, wires)
