name = "Wired"
uuid = "09f8ee52-9d6d-4c1a-8fd3-94aced8f6107"
authors = ["ryan@freestatelabs"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
